### ISSUE TITLE
[front] 채팅방 소켓 구현현황

### ISSUE THREAD

**Issue by parktest0325** [3DPong/transcendence#135]
명세 : #133 

# TODO List
## Feat : 로그인 이후 listen
- [x] 초대 이벤트 (event: alarm, type: invite) : 초대됐을때 내 채팅방 리스트에 추가 + 알람을 위해 발생 (메시지 없음)
- [x] 밴 이벤트 (event: alarm, type: ban) : 내 채팅방 리스트에서 제거 + 알람
- [x] 킥 이벤트 (event: alarm, type: kick) : 내 채팅방 리스트에서 제거 + 알람
- [ ] 채팅 이벤트 (event: alarm, type: chat) : 어떤 채팅방에 채팅 메시지가 왔는지 카운트를 위한 이벤트

#### 요청
- [x] 참여 이벤트 (event: enter-chat) : 내가 참여했다는 이벤트. chat_active에 join하는것을 요청하기 위함
- [x] 밴 (event: ban-chat) : 밴, 언밴, 킥, 뮤트에 대한 요청
- [x] 언밴 (event: unban-chat)
- [x] 킥 (event: kick-chat)
- [x] 뮤트 (event: mute-chat) : 언뮤트는 동일한 이벤트 사용
- [x] 메시지 전송 (event: message-chat) : 메시지 전송 요청
- [x] 권한 변경 (API)
- [x] 나가기 이벤트 (event: leave-chat) : 내가 채팅방에서 나갔다는 이벤트. chat_active에서 leave 하는것을 요청

#### 리슨
- [x] 메시지 (event: chat) : 누군가가 메시지를 보내면(message-chat) 서버에서 생성 후 응답받는 메시지를 메시지리스트에 추가
- [x] 킥 (event: kick) : 유저리스트에서 deleted_at 에 현재시간 넣기
- [x] 밴 (event: ban) : 유저리스트에서 deleted_at 에 현재시간 넣기, 밴리스트에 추가 + setTimeout
- [x] 뮤트 (event: mute) : 뮤트리스트에 추가 + setTimeout
- [x] 다른유저의 참여 (event: user, type: enter) : 유저리스트에 추가
- [x] 다른유저의 나가기 (event: user, type: leave) : 유저리스트에서 delete_at에 현재시간 넣기
- [x] 에러 (event: error) : 소켓으로 특정 작업 요청시 (message 전송, 킥, 밴, 뮤트 등의 작업) 에러가 발생한 경우 에러출력
- [x] 권한 변경 (event: role) : 누군가의 권한이 변경된경우 유저리스트에서 권한변경

## Fix
- [x] 뮤트, 밴 등 현재시간을 new Date() 기준(KST)으로 변경 (현재는 UTC)
- [ ] 소켓 연결을 로그인 이후 최상단으로 변경필요
- [x] 당사자가 강퇴(밴, 킥)당한 경우 채널로 리다이렉트
- [x] 언뮤트 백엔드 코드 수정되면 연결 다시해야할듯 
- [ ] 킥, 밴, 초대 알람도 최상단에서 on 해야함. 
- [ ] 채팅메세지카운트도 최상단으로교환
- [x] 권한 변경하면 나머지 컴포넌트에 전파돼야하는데 안됨 ???

# 구현중 추가 요청사항
- [x] chat_alarm 룸으로 받는 chat 메시지를 alarm, type:chat 으로 변경 필요 
- [x] 한번 나간방에 다시 초대된 경우 deleted_at이 초기화되지 않아서 유저리스트에 추가되지 않음. => null로 업데이트 필요
- [x] 언뮤트 메시지가 안옴
- [x] 없어도 기능상 문제는 없는데, 밴 해제나 킥을 하면 메시지에 닉네임이 null로 표시됨

**Comment by kyu-baek** [comment]
특정 채팅방 상세 페이지에 있던 유저가, alarm 타입 ban or kick 을 받았을 때
  1. channel_id 를 확인해서 지금 상세 채팅방이 해당 채팅방인지 확인
  2. 만약 해당 채팅방과 동일하다면, 프론트에서 백으로 leave-chat 이벤트를 요청해서, active_chat_${channel_id} 을 leave 할 수 있도록 해주어야 함.

**Comment by kyu-baek** [comment]
ban 과 unban,
mute 와 unmute

 이 두가지는 end_at 이 포함되어 있는지 아닌지에 따라 구별하시는 게 좋을 것 같습니다. mute 를 시킬 때, ban 을 시킬 때는 반환값에 end_at 이 포함되지만, 해제할 때는 포함되지 않습니다.

그래서 굳이 따로 type 을 지정해서,

.emit('ban', { type:'ban or unban'  -> 이런식으로 구분할 필요는 없을 것 같습니다.
