### ISSUE TITLE
[back, front] 버그 리포트

### ISSUE THREAD

**Issue by csstring** [3DPong/transcendence#199]
### 오류 상황
- [x] 게임중에 게임선택창 다시 누르면 게임 exit 하는게 아니라 새로고침 되면서 멈춤 상대방은 계속 게임 진행 (#205 게임중에 선택창을 못누르도록 ui를 숨김으로서 해결함)
- [x] 게임 시작 전 키 누르면 튕김 (#200 으로 fix)
- [x] 이미지 안넣었을 때 이유 알려줘야함 (#205 회원가입시 이미지 꼭 넣어야 합니다 메시지 띄워줌)
- [x] 온라인 상태 처음에 반영안됨 (#205 수정 완료)
- [x] 프로필만 바꾸는거 닉네임 인증 절차 때문에 안됨 (#205 수정 완료)

- [x] 관전 누르면 에러발생(UserData : Validation failed (numeric string is expected)
- [x] 채팅방에서 게임 방이 사라진 초대메세지에 대해 게임 참가나 관전 누르면 게임 로딩 화면으로 넘어가버림(맨 처음에는 참가나 관전 누르면 이런 현상이 없는데 채팅방에서 게임 한번 하고 나서 시도하면 오류발생)
- [x] Total:0 Win:0 Lose:0 Level:0 총 전적 변하지 않음 (#201 fix)
- [x] 게임 초대 안됨(아마 #198 pr 반영되면 수정될듯)
- [x] 채팅 이미지 변경 badrequest 발생 (full url을 안줘서 발생)
- [x] 채팅방 이름 변경 안됨
- [x] 게임이 정상 종료 되도 10 대 0 으로 고정됨 (#203 fix)
- [x] 채팅방 들어 가자마자 "Socket Error 권한이 없습니다!" 발생(방장인 경우 발생하는 것 같음, 이상해서 새로고침 해봤더니 정상작동(??))
- [x] 채팅방을 만드는 시점에 초대하는건 되는데 만들어진 뒤에  초대 하는건 안됩니다

**Comment by csstring** [comment]
게임 중간에 탈주하면 10대 0 되는건 몰수패고 일부러 구현한 사항이라 냅두겠습니다

**Comment by kimminkyeu** [comment]
프로필 이미지 업데이트는 되지만 메시지창이 에러메시지처럼 표시되고있습니다. (메시지 내용: 닉네임은 이미 존재합니다. 이미지만 업데이트 합니다)
이미지와 닉네임 둘다 안바뀌었을때만 메시지를 띄우도록 수정하겠습니다.

**Comment by kimminkyeu** [comment]
관전자 키 입력이 되는 문제 : 프론트에서도 키 이벤트 등록이 되는지 체크해서 수정하겠습니다

**Comment by csstring** [comment]
채팅방에서 게임 방이 사라진 초대메세지에 대해 게임 참가나 관전 누르면 게임 로딩 화면으로 넘어가버림

이거 지금 해보니까 오류 없어진건 같은데 제가 예전 버전으로 테스트를 해봤어서 문제가 생겼던건지 코드가 코쳐진건지 모르겠네요

**Comment by parktest0325** [comment]
채팅방 이름변경안됨 : 기본썸네일일때 채팅방 수정하면 CORS에러가 발생해서 적용이 안되는 버그인거같은데 확인해보겟습니다
채팅방 처음 접근시 권한없음 : 이건 소켓 끊기고 채팅방 접속할때 발생하는 에러랑 동일해보이네요

**Comment by JuneParkCode** [comment]
채팅방명에 숫자가 들어가면 생성이 안됩니다.
