### ISSUE TITLE
[back] production 환경, develop 환경 분리 + 도커 관련 수정

### ISSUE THREAD

**Issue by JuneParkCode** [3DPong/transcendence#37]
## 환경변수
현재는 `env.dev` 의 환경변수를 기반으로 실행되고 있습니다. 하지만, 실제로는 production 과 develop 모드가 각각 구분이 되기 때문에 서로 다른 환경 변수를 사용합니다.

### TODO
- [x] NODE_ENV  값을 활용해서 PRODUCTION | DEVELOP 모드 구분

## DOCKER
배포 환경과 개발 환경의 분리를 위해서 도커 컨테이너 관련 수정을 하겠습니다.
### TODO
- [ ] 배포용 컨테이너 생성
- [ ] 개발용 컨테이너 생성 (다른 포트 사용)
